### PR TITLE
Fix issue with using Logic in minisat file

### PR DESCRIPTION
**Pull request by tmeasday**
@dgreensp I'm not sure if you'll get this, but I'd like to release this as 2.0.1 -- the 2.0.0 version does not actually work due to references to `Logic` inside the `minisat_wrapper` file.

### CODE REVIEW

**Comment by tmeasday** [comment]
(I have commit rights to this repo, but I can't publish the npm package)

**Comment by dgreensp** [comment]
Hi Tom!

The pattern for asserting within `logic-solver.js` is to write out `if (assert) assert(...)`, so the added code should do that for consistency.  Other than that, LGTM.  I'm happy to republish.

**Comment by tmeasday** [comment]
Done!

**Comment by dgreensp** [comment]
Cool, tell me when and which branch and I can re-publish if that works.

**Comment by tmeasday** [comment]
It's here on the `devel` branch.

**Comment by dgreensp** [comment]
Published as 2.0.1.  Please bump version in `package.json`! :)

**Comment by tmeasday** [comment]
Oh, sure! Thanks @dgreensp. Should I grant you commit access to this repo?

**Comment by dgreensp** [comment]
That would be great

**Pull request merged**
